# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1514657451);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1514668981);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1514657331);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1514669131);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1514657210);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 40);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161005044426");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.defaultBrowserCheckCount", 1);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "https://github.com/Portergos/portergos-iso");
user_pref("browser.startup.homepage_override.buildID", "20161005044426");
user_pref("browser.startup.homepage_override.mstone", "49.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"downloads-button\",\"home-button\",\"bookmarks-menu-button\",\"pocket-button\",\"ublock0-button\",\"firefox_ghostery_com-browser-action\",\"_de22fd49-c9ab-4359-b722-b3febdc3a0b0_-browser-action\",\"_5657c026-efc3-4860-b43b-16e4eaa8a9aa_-browser-action\",\"https-everywhere-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"ublock0-button\",\"firefox_ghostery_com-browser-action\",\"_de22fd49-c9ab-4359-b722-b3febdc3a0b0_-browser-action\",\"_5657c026-efc3-4860-b43b-16e4eaa8a9aa_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"uBlock0@raymondhill.net\":{\"version\":\"1.13.8\",\"type\":\"extension\",\"descriptor\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/uBlock0@raymondhill.net.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false,\"dependencies\":[]},\"firefox@ghostery.com\":{\"version\":\"8.0.2.4\",\"type\":\"webextension\",\"descriptor\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/firefox@ghostery.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false,\"dependencies\":[]},\"{de22fd49-c9ab-4359-b722-b3febdc3a0b0}\":{\"version\":\"0.4.2\",\"type\":\"webextension\",\"descriptor\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/{de22fd49-c9ab-4359-b722-b3febdc3a0b0}.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false,\"dependencies\":[]},\"enhancerforyoutube@maximerf.addons.mozilla.org\":{\"version\":\"2.0.17\",\"type\":\"webextension\",\"descriptor\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/enhancerforyoutube@maximerf.addons.mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false,\"dependencies\":[]},\"{5657c026-efc3-4860-b43b-16e4eaa8a9aa}\":{\"version\":\"0.4.8\",\"type\":\"webextension\",\"descriptor\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/{5657c026-efc3-4860-b43b-16e4eaa8a9aa}.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false,\"dependencies\":[]}}");
user_pref("extensions.databaseSchema", 18);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "https-everywhere%40eff.org:5.2.21,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1514657452);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.https_everywhere.firstrun_context_menu", false);
user_pref("extensions.https_everywhere.prefs_version", 1);
user_pref("extensions.https_everywhere.toolbar_hint_shown", true);
user_pref("extensions.lastAppVersion", "49.0");
user_pref("extensions.lastPlatformVersion", "49.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.ublock0.shortcuts.launch-element-picker", "");
user_pref("extensions.ublock0.shortcuts.launch-element-zapper", "");
user_pref("extensions.ublock0.shortcuts.launch-logger", "");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"firefox@ghostery.com\":\"1dd426e6-1774-4c1c-a73d-d9d42360b79c\",\"{de22fd49-c9ab-4359-b722-b3febdc3a0b0}\":\"fec5dc15-c726-4fcb-a0cf-de0eff90d562\",\"enhancerforyoutube@maximerf.addons.mozilla.org\":\"e29f0046-d1ae-4f5a-a01d-a22245a08289\",\"{5657c026-efc3-4860-b43b-16e4eaa8a9aa}\":\"c2555972-c018-446f-b1b3-220488b639a4\"}");
user_pref("extensions.xpiState", "{\"app-profile\":{\"https-everywhere@eff.org\":{\"d\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/https-everywhere@eff.org.xpi\",\"e\":true,\"v\":\"5.2.21\",\"st\":1514657569000},\"{5657c026-efc3-4860-b43b-16e4eaa8a9aa}\":{\"d\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/{5657c026-efc3-4860-b43b-16e4eaa8a9aa}.xpi\",\"e\":true,\"v\":\"0.4.8\",\"st\":1514657551000},\"enhancerforyoutube@maximerf.addons.mozilla.org\":{\"d\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/enhancerforyoutube@maximerf.addons.mozilla.org.xpi\",\"e\":true,\"v\":\"2.0.17\",\"st\":1514657527000},\"{de22fd49-c9ab-4359-b722-b3febdc3a0b0}\":{\"d\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/{de22fd49-c9ab-4359-b722-b3febdc3a0b0}.xpi\",\"e\":true,\"v\":\"0.4.2\",\"st\":1514657494000},\"firefox@ghostery.com\":{\"d\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/firefox@ghostery.com.xpi\",\"e\":true,\"v\":\"8.0.2.4\",\"st\":1514657375000},\"uBlock0@raymondhill.net\":{\"d\":\"/home/liveuser/.light/light/d6i72un5.default/extensions/uBlock0@raymondhill.net.xpi\",\"e\":true,\"v\":\"1.13.8\",\"st\":1514657305000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/home/liveuser/Downloads/home/${USER}/usr/lib/light/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"49.0\",\"st\":1475680718000}}}");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.prefetch-next", false);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.blocklist.addons.checked", 1514668645);
user_pref("services.blocklist.clock_skew_seconds", 336);
user_pref("services.blocklist.gfx.checked", 1514668645);
user_pref("services.blocklist.last_etag", "\"1492010695571\"");
user_pref("services.blocklist.last_update_seconds", 1514668645);
user_pref("services.blocklist.onecrl.checked", 1514668645);
user_pref("services.blocklist.plugins.checked", 1514668645);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1514669010);
